/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { AddressCache } from "../AddressCache";

export class AddressCache__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressCache {
    return new Contract(address, _abi, signerOrProvider) as AddressCache;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "name",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "CachedAddressUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract IAddressStorage",
        name: "_addressStorage",
        type: "address",
      },
    ],
    name: "updateAddressCache",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
