/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDebtSystem } from "../IDebtSystem";

export class IDebtSystem__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDebtSystem {
    return new Contract(address, _abi, signerOrProvider) as IDebtSystem;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_currency",
        type: "bytes32",
      },
    ],
    name: "GetUserDebtBalanceInUsd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_debtProportion",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_factor",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_currency",
        type: "bytes32",
      },
    ],
    name: "UpdateDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
