/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDexPriceHelper } from "../IDexPriceHelper";

export class IDexPriceHelper__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDexPriceHelper {
    return new Contract(address, _abi, signerOrProvider) as IDexPriceHelper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    name: "getPairPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
