/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { SafeDecimalMath } from "../SafeDecimalMath";

export class SafeDecimalMath__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<SafeDecimalMath> {
    return super.deploy(overrides || {}) as Promise<SafeDecimalMath>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SafeDecimalMath {
    return super.attach(address) as SafeDecimalMath;
  }
  connect(signer: Signer): SafeDecimalMath__factory {
    return super.connect(signer) as SafeDecimalMath__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeDecimalMath {
    return new Contract(address, _abi, signerOrProvider) as SafeDecimalMath;
  }
}

const _abi = [
  {
    inputs: [],
    name: "PRECISE_UNIT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNIT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "highPrecisionDecimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "preciseUnit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "unit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x61012c610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060655760003560e01c8063313ce56714606a578063864029e7146086578063907af6c014609e5780639d8e21771460a4578063d5e5e6e61460aa578063def4419d1460b0575b600080fd5b607060b6565b6040805160ff9092168252519081900360200190f35b608c60bb565b60408051918252519081900360200190f35b608c60ca565b608c60d6565b608c60e2565b607060f1565b601281565b676765c793fa10079d601b1b81565b670de0b6b3a764000090565b670de0b6b3a764000081565b676765c793fa10079d601b1b90565b601b8156fea26469706673582212202186be681e9933c6c8a957dade9f2c06be65af869cbd7ef16d78660da49ccf4b64736f6c634300060c0033";
