/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AssetSystemInterface extends ethers.utils.Interface {
  functions: {
    "__AdminUpgradeable_init(address)": FunctionFragment;
    "addAsset(address)": FunctionFragment;
    "addressMap(bytes32)": FunctionFragment;
    "admin()": FunctionFragment;
    "assetNumber()": FunctionFragment;
    "becomeAdmin()": FunctionFragment;
    "candidate()": FunctionFragment;
    "forbidAssets(bytes32)": FunctionFragment;
    "getAddress(bytes32)": FunctionFragment;
    "getAddressWithRequire(bytes32,string)": FunctionFragment;
    "getAssetAddresses()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isAsset(address)": FunctionFragment;
    "isForbidden(bytes32)": FunctionFragment;
    "mAddress2Names(address)": FunctionFragment;
    "mAssetList(uint256)": FunctionFragment;
    "removeAsset(bytes32)": FunctionFragment;
    "setCandidate(address)": FunctionFragment;
    "setForbidAsset(bytes32,bool)": FunctionFragment;
    "totalAssetsInUsd()": FunctionFragment;
    "update(bytes32,address)": FunctionFragment;
    "updateAll(bytes32[],address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__AdminUpgradeable_init",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "addAsset", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addressMap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "becomeAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "candidate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forbidAssets",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressWithRequire",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "isAsset", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isForbidden",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mAddress2Names",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mAssetList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCandidate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setForbidAsset",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssetsInUsd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAll",
    values: [BytesLike[], string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "__AdminUpgradeable_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addressMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "becomeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "candidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forbidAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressWithRequire",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isForbidden",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mAddress2Names",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mAssetList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForbidAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssetsInUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateAll", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "AssetAdded(bytes32,address)": EventFragment;
    "AssetForbid(bytes32,address,bool)": EventFragment;
    "AssetRemoved(bytes32,address)": EventFragment;
    "CandidateChanged(address,address)": EventFragment;
    "StorageAddressUpdated(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetForbid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CandidateChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StorageAddressUpdated"): EventFragment;
}

export class AssetSystem extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AssetSystemInterface;

  functions: {
    __AdminUpgradeable_init(
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "__AdminUpgradeable_init(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addAsset(
      asset: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addAsset(address)"(
      asset: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addressMap(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "addressMap(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    "admin()"(overrides?: CallOverrides): Promise<[string]>;

    assetNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    "assetNumber()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    becomeAdmin(overrides?: Overrides): Promise<ContractTransaction>;

    "becomeAdmin()"(overrides?: Overrides): Promise<ContractTransaction>;

    candidate(overrides?: CallOverrides): Promise<[string]>;

    "candidate()"(overrides?: CallOverrides): Promise<[string]>;

    forbidAssets(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "forbidAssets(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAddressWithRequire(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getAddressWithRequire(bytes32,string)"(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAssetAddresses(overrides?: CallOverrides): Promise<[string[]]>;

    "getAssetAddresses()"(overrides?: CallOverrides): Promise<[string[]]>;

    initialize(
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isAsset(asset: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isAsset(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isForbidden(name: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "isForbidden(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mAddress2Names(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    "mAddress2Names(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    mAssetList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "mAssetList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeAsset(
      name: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeAsset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCandidate(
      _candidate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCandidate(address)"(
      _candidate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setForbidAsset(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setForbidAsset(bytes32,bool)"(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    totalAssetsInUsd(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { total: BigNumber }>;

    "totalAssetsInUsd()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { total: BigNumber }>;

    update(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "update(bytes32,address)"(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateAll(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateAll(bytes32[],address[])"(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  __AdminUpgradeable_init(
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "__AdminUpgradeable_init(address)"(
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addAsset(asset: string, overrides?: Overrides): Promise<ContractTransaction>;

  "addAsset(address)"(
    asset: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addressMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "addressMap(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  admin(overrides?: CallOverrides): Promise<string>;

  "admin()"(overrides?: CallOverrides): Promise<string>;

  assetNumber(overrides?: CallOverrides): Promise<BigNumber>;

  "assetNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

  becomeAdmin(overrides?: Overrides): Promise<ContractTransaction>;

  "becomeAdmin()"(overrides?: Overrides): Promise<ContractTransaction>;

  candidate(overrides?: CallOverrides): Promise<string>;

  "candidate()"(overrides?: CallOverrides): Promise<string>;

  forbidAssets(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "forbidAssets(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAddress(name: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getAddress(bytes32)"(
    name: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getAddressWithRequire(
    name: BytesLike,
    reason: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAddressWithRequire(bytes32,string)"(
    name: BytesLike,
    reason: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getAssetAddresses(overrides?: CallOverrides): Promise<string[]>;

  "getAssetAddresses()"(overrides?: CallOverrides): Promise<string[]>;

  initialize(
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  "isAsset(address)"(
    asset: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isForbidden(name: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "isForbidden(bytes32)"(
    name: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mAddress2Names(arg0: string, overrides?: CallOverrides): Promise<string>;

  "mAddress2Names(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  mAssetList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "mAssetList(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  removeAsset(
    name: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeAsset(bytes32)"(
    name: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCandidate(
    _candidate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setCandidate(address)"(
    _candidate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setForbidAsset(
    name: BytesLike,
    forbid: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setForbidAsset(bytes32,bool)"(
    name: BytesLike,
    forbid: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  totalAssetsInUsd(overrides?: CallOverrides): Promise<BigNumber>;

  "totalAssetsInUsd()"(overrides?: CallOverrides): Promise<BigNumber>;

  update(
    name: BytesLike,
    dest: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "update(bytes32,address)"(
    name: BytesLike,
    dest: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateAll(
    names: BytesLike[],
    destinations: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateAll(bytes32[],address[])"(
    names: BytesLike[],
    destinations: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    __AdminUpgradeable_init(
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "__AdminUpgradeable_init(address)"(
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addAsset(asset: string, overrides?: CallOverrides): Promise<void>;

    "addAsset(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addressMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "addressMap(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    admin(overrides?: CallOverrides): Promise<string>;

    "admin()"(overrides?: CallOverrides): Promise<string>;

    assetNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "assetNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    becomeAdmin(overrides?: CallOverrides): Promise<void>;

    "becomeAdmin()"(overrides?: CallOverrides): Promise<void>;

    candidate(overrides?: CallOverrides): Promise<string>;

    "candidate()"(overrides?: CallOverrides): Promise<string>;

    forbidAssets(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "forbidAssets(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getAddressWithRequire(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAddressWithRequire(bytes32,string)"(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getAssetAddresses(overrides?: CallOverrides): Promise<string[]>;

    "getAssetAddresses()"(overrides?: CallOverrides): Promise<string[]>;

    initialize(_admin: string, overrides?: CallOverrides): Promise<void>;

    "initialize(address)"(
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

    "isAsset(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isForbidden(name: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "isForbidden(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mAddress2Names(arg0: string, overrides?: CallOverrides): Promise<string>;

    "mAddress2Names(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    mAssetList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "mAssetList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    removeAsset(name: BytesLike, overrides?: CallOverrides): Promise<void>;

    "removeAsset(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setCandidate(_candidate: string, overrides?: CallOverrides): Promise<void>;

    "setCandidate(address)"(
      _candidate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setForbidAsset(
      name: BytesLike,
      forbid: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setForbidAsset(bytes32,bool)"(
      name: BytesLike,
      forbid: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    totalAssetsInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAssetsInUsd()"(overrides?: CallOverrides): Promise<BigNumber>;

    update(
      name: BytesLike,
      dest: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "update(bytes32,address)"(
      name: BytesLike,
      dest: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAll(
      names: BytesLike[],
      destinations: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "updateAll(bytes32[],address[])"(
      names: BytesLike[],
      destinations: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AdminChanged(oldAdmin: null, newAdmin: null): EventFilter;

    AssetAdded(name: null, asset: null): EventFilter;

    AssetForbid(name: null, asset: null, fidbid: null): EventFilter;

    AssetRemoved(name: null, asset: null): EventFilter;

    CandidateChanged(oldCandidate: null, newCandidate: null): EventFilter;

    StorageAddressUpdated(name: null, addr: null): EventFilter;
  };

  estimateGas: {
    __AdminUpgradeable_init(
      _admin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "__AdminUpgradeable_init(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addAsset(asset: string, overrides?: Overrides): Promise<BigNumber>;

    "addAsset(address)"(
      asset: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addressMap(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "addressMap(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    "admin()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "assetNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    becomeAdmin(overrides?: Overrides): Promise<BigNumber>;

    "becomeAdmin()"(overrides?: Overrides): Promise<BigNumber>;

    candidate(overrides?: CallOverrides): Promise<BigNumber>;

    "candidate()"(overrides?: CallOverrides): Promise<BigNumber>;

    forbidAssets(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "forbidAssets(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressWithRequire(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressWithRequire(bytes32,string)"(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAssetAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    "getAssetAddresses()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(_admin: string, overrides?: Overrides): Promise<BigNumber>;

    "initialize(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isAsset(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isAsset(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isForbidden(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "isForbidden(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mAddress2Names(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "mAddress2Names(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mAssetList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mAssetList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAsset(name: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "removeAsset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCandidate(_candidate: string, overrides?: Overrides): Promise<BigNumber>;

    "setCandidate(address)"(
      _candidate: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setForbidAsset(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setForbidAsset(bytes32,bool)"(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    totalAssetsInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAssetsInUsd()"(overrides?: CallOverrides): Promise<BigNumber>;

    update(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "update(bytes32,address)"(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateAll(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateAll(bytes32[],address[])"(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __AdminUpgradeable_init(
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "__AdminUpgradeable_init(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addAsset(
      asset: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addAsset(address)"(
      asset: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addressMap(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressMap(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "admin()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetNumber()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    becomeAdmin(overrides?: Overrides): Promise<PopulatedTransaction>;

    "becomeAdmin()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    candidate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "candidate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    forbidAssets(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "forbidAssets(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddress(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressWithRequire(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressWithRequire(bytes32,string)"(
      name: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAssetAddresses()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAsset(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isForbidden(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isForbidden(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mAddress2Names(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "mAddress2Names(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mAssetList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "mAssetList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAsset(
      name: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeAsset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCandidate(
      _candidate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCandidate(address)"(
      _candidate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setForbidAsset(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setForbidAsset(bytes32,bool)"(
      name: BytesLike,
      forbid: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    totalAssetsInUsd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalAssetsInUsd()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    update(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "update(bytes32,address)"(
      name: BytesLike,
      dest: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateAll(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateAll(bytes32[],address[])"(
      names: BytesLike[],
      destinations: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
